#
# default configuration setting for spring application context
#
mdpnp.domain=0
mdpnp.fhir.url=
himss.domain=2

mdpnp.apps.patient.database=jdbc:hsqldb:file:~/icepatientdb
#mdpnp.apps.patient.database=jdbc:hsqldb:mem:icepatientdb

dds.discovery.peers=
#dds.discovery.peers=239.255.0.1,127.0.0.1

mdpnp.fhir.token.url=http://localhost:9080/auth/realms/test/protocol/openid-connect/token
mdpnp.fhir.token.user=testuser
mdpnp.fhir.token.password=testpass
mdpnp.fhir.token.clientId=my-fhir-client
mdpnp.fhir.backend.url=http://localhost:8099/fhir
mdpnp.fhir.patient.identifier.system=urn:oid:2.16.840.1.113883.3.1974
