#
# default configuration setting for spring application context
#
mdpnp.domain=0
mdpnp.fhir.url=
himss.domain=2

mdpnp.apps.patient.database=jdbc:hsqldb:file:~/icepatientdb
#mdpnp.apps.patient.database=jdbc:hsqldb:mem:icepatientdb

dds.discovery.peers=
#dds.discovery.peers=239.255.0.1,127.0.0.1

# ===================================================================
# Esto es la configuracion que se necesita para poder hacer un fetch
# a una api HAPI con un KeyCloak como gateway. Los valores de abajo
# estan por defecto en el realm "test" pero realmente podemos cambiar
# por otros realms con diferentes usuarios. Revisar la documentacion
# explicando como funciona esta conexion. (docs/HL7-FHIR Exporter.md)
# ===================================================================

# mdpnp.fhir.token.url=http://localhost:9080/auth/realms/test/protocol/openid-connect/token
# mdpnp.fhir.token.user=testuser
# mdpnp.fhir.token.password=testpass
# mdpnp.fhir.token.clientId=my-fhir-client
# mdpnp.fhir.list.auth=patient-list-example

# mdpnp.fhir.token.url=http://localhost:9080/auth/realms/<realm>/protocol/openid-connect/token
# mdpnp.fhir.token.user=<user>
# mdpnp.fhir.token.password=<password>
# mdpnp.fhir.token.clientId=<client_id>
# mdpnp.fhir.list.auth=<list_name>

mdpnp.fhir.token.url=http://localhost:9080/auth/realms/fhir-quirofano/protocol/openid-connect/token
mdpnp.fhir.token.user=dr.gomez
mdpnp.fhir.token.password=demo1234
mdpnp.fhir.token.clientId=fhir-professional-app
mdpnp.fhir.list.auth=lista-dr-gomez

mdpnp.fhir.backend.url=http://localhost:8099/fhir
mdpnp.fhir.patient.identifier.system=urn:oid:2.16.840.1.113883.3.1974

